# Introdução ao Processamento de Linguagem Natural com PyTorch

The goals for this chapter are to:

* Develop a clear understanding of the supervised learning paradigm, understand terminology, and develop a conceptual framework to approach learning tasks for future chapters.
* Learn how to encode inputs for the learning tasks.
* Understand what computational graphs are.
* Master the basics of PyTorch

## Aprendizado Supervisionado


## Básico de PyTorch

### Tipos de Dados no PyTorch

* Escalares - valores numéricos isolados
* Vetores - arranjos unidimensionais (listas) de valores numéricos
* Matrizes - arranjos bidimensionais (tabelas) de valores nunméricos
* Tensores - arranjos n-dimensionais (acima de 2 dimensões) de valores numéricos

### Criação de Tensores de valores Aleatórios 

A biblioteca PyTorch permite a criação de tensores de diversas formas por meio de seu pacote `torch`. 
Uma das formas de se criar um tensor é por meio da inicialização aleatória de seus valores, após a especificação de suas
dimensões.

Antes de fornecermos um exemplo, é necessário importar o pacote `torch`.
Para garantir a reprodutibilidade do exemplo, iremos inicializar o gerador de números aleatórios do PyThorch com a
semente `1234`:

```python
import torch
torch.manual_seed(1234)
```   

In [9]:
import torch
torch.manual_seed(1234)

Antes de criarmos nosso primeiro tensor iremos definir a função `describe(x)` cujo objetivo é a sumarização das
principais propriedades de um tensor por meio da chamada/acesso a métodos/atributos da classe `tensor` bem como da
exibição de sues valores:

* seu tipo: método `x.type();
* suas dimensões: atributo `x.shape`; e
* seus valores: `x`.

```python
def describe(x):
    print(f'Type: {x.type()}')
    print(f'Shape/size: {x.shape}')
    print(f'Values: \n{x}')
```

In [10]:
def describe(x):
    print(f'Type: {x.type()}')
    print(f'Shape/size: {x.shape}')
    print(f'Values: \n{x}')

#### Exemplo - Criação de um tensor com valores aleatórios quaisquer:

É chegada a hora de criarmos nosso primeiro tensor. Ele terá as dimensões `(2,3)` e seus valores serão inicializados
de forma aleatória. Iremos chamar a função `describe(x)` para visualizarmos suas proprieadades e seu conteúdo: 

```python
describe(torch.Tensor(2, 3))
```

In [11]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.0979e-05, 1.3030e-11, 6.6526e+22],
        [4.2423e-08, 2.0971e-07, 2.0470e+23]])


É possível criar tensores cujos elementos sejam obtidos, aleatoriamente, a partir de distribuições de probabilidade 
previamente especificadas:

#### Exemplo - Criação de um tensor cujos elementos correspondem a uma variável aleatória oriunda de uma distribuição de probabilidades Uniforme, definida no intervalo $[0, 1)$:

```python
describe(torch.rand(2,3)) # distribuição uniforme no intervalo [0, 1)
```

In [12]:
describe(torch.rand(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


#### Exemplo - Criação de um tensor cujos elementos correspondem a uma variável aleatória oriunda de uma distribuição de probabilidades Normal:

```python
describe(torch.randn(2,3)) # distribuição normal
```

In [13]:
describe(torch.randn(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.8545,  0.5098, -0.0821],
        [ 0.6607,  0.0785,  0.7884]])


### Criação de Tensores preenchidos com um mesmo escalar

Tensores podem ser preenchidos com um mesmo escalar tanto no momento de sua criação como também num momento posterior.

No momento de sua criação, podemos definir que seus valores sejam todos iguais a $0$ (`torch.zeros()`) ou a $1$ 
(`torch.ones()`).

#### Exemplo - Criação de vetor de $0$'s
```python
describe(torch.zeros(2,3))
```

In [15]:
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Exemplo - Criação de vetor de $1$'s
```python
describe(torch.ones(2,3))
```

In [16]:
describe(torch.ones(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Caso desejemos preencher os elementos de um tensor com valores escalares diferentes de $0$ e $1$, 
será necessário chamar o método `fill_()` para um objeto do tipo `tensor` num momento posterior à sua criação. 

#### Exemplo - preenchimento de um tensor preexistente com um escalar

```python
# cria vetor x com elementos aleatórios
x = torch.rand(2,3)
describe(x)

# preenche x com o escalar 3.3
x.fill_(3.3)
describe(x)
```

In [20]:
# cria vetor x com elementos aleatórios
x = torch.rand(2,3)
describe(x)

# preenche x com o escalar 3.3
x.fill_(3.3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.6662, 0.3343, 0.7893],
        [0.3216, 0.5247, 0.6688]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[3.3000, 3.3000, 3.3000],
        [3.3000, 3.3000, 3.3000]])


> **nota:** métodos cujos nomes terminam com o caractere `_`, como `fill_n`, correspondem a operações do tipo 
> *in-place*. Tais operações têm efeito sobre o conteúdo do próprio objeto e não sobre uma cópia do mesmo.

### Criação de Tensores de forma declarativa

PyTorch permite a criação de tensores de forma declarativa, por meio da especificação dos valores de seus elementos. 
Tais valores podem ser fornecidos por meio de *listas* ou através de *arrays* do tipo NumPy.

#### Exemplo - Criação de um tensor a partir de *listas* 

```python
x = torch.Tensor([[0, 1, 1],
                  [2, 3, 5]])

describe(x)
```

In [26]:
x = torch.Tensor([[0, 1, 1],
                  [2, 3, 5]])

describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 1.],
        [2., 3., 5.]])


#### Exemplo - Criação de um tensor a partir de um *array* NumPy 

```python
import numpy as np

np_array = np.random.rand(2, 3) # criação de um array NumPy (2,3) a partir de uma dist. uniforme
x = torch.from_numpy(np_array)  # criação de um tensor PyTorch a partir de np_array

describe(x)
```

In [22]:
import numpy as np

np_array = np.random.rand(2, 3) # criação de um array NumPy (2,3) a partir de uma dist. uniforme
x = torch.from_numpy(np_array)  # criação de um tensor PyTorch a partir de np_array

describe(x)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1615, 0.7033, 0.5173],
        [0.3792, 0.3803, 0.5399]], dtype=torch.float64)


## Tipos e Dimensões de Tensores
